### ISSUE TITLE
Apostrphes in CustomMessages break syntax highlighting

### ISSUE THREAD

**Issue by Gruntfuggly** [idleberg/vscode-innosetup#1]
I've just started using Inno and was pleased to find an extension for VSCode that supports it! 

The setup file that I'm working on has a custom message:
`Perform am optional self test on any dongle connected to the computer's USB port.`

This breaks the highlighting because there is no closing apostrophe. I've temporarily disabled the apostrophe highlighting as a workaround, but I wonder if there is another solution?

**Comment by idleberg** [comment]
Thanks for reporting, will look into it.

**Comment by Gruntfuggly** [comment]
On 2017-01-12 19:51, Jan T. Sott wrote: 

> Can you please give me a minimal real-world example?

If I create a file with just the following, everything after the
apostrophe is shown in green. 

[Messages]
ExampleMessage=This message's text contains an apostrophe 

[Code]
function IsTrue(): Boolean;
begin
 Result := True;
end; 

Cheers, 

Nige

**Comment by idleberg** [comment]
Please take a look at [950a1cd5](https://github.com/idleberg/vscode-innosetup/blob/950a1cd5ee934b83c9a42d3493b321b2c67bf693/syntaxes/inno-setup.tmLanguage)

**Comment by Gruntfuggly** [comment]
That looks like it's working fine. Thanks!

**Comment by pzhlkj6612** [comment]
Unfortunately, the fix in 950a1cd5ee934b83c9a42d3493b321b2c67bf693 has been overwritten by f03241e5fed011ee7794f7321693aab6d40606f4 .
