### ISSUE TITLE
Support for relative paths

### ISSUE THREAD

**Issue by dimastij** [idleberg/vscode-innosetup#11]
I got a build tools folder with inno setup in my project that I would like to use.
Is it possible to use "pathToIscc" as path like in the following example?

`"innosetup.pathToIscc": "${workspaceFolder}\\BuildTools\\InnoSetup\\ISCC.exe"`

**Comment by idleberg** [comment]
Haven't you tried it before posting the issue?!

**Comment by idleberg** [comment]
Variable substitution for package settings is now supported as of v1.6.0!
