### ISSUE TITLE
[Feature request]: syntax highlighting also works in [code] section

### ISSUE THREAD

**Issue by westr029** [idleberg/vscode-innosetup#24]
Currently the syntax highlighting works in all sections for inno setup, except for the `[code]` section. See the example below:
![afbeelding](https://user-images.githubusercontent.com/25100691/95468311-ac872780-097e-11eb-9e25-68aa6e91c6f8.png)

Would be nice if syntax highlighting also works in this section.

**Comment by idleberg** [comment]
Since the code section contains Pascal code, you need to install a separate syntax highlighter for that. Versions prior to v1.3.0 installed [alefragnani.pascal](https://marketplace.visualstudio.com/items?itemName=alefragnani.pascal), but that made it harder to choose other highlighters.
