### ISSUE TITLE
Support for additional line comment syntax

### ISSUE THREAD

**Issue by dylankenneally** [idleberg/vscode-innosetup#6]
I've noticed that `;` is used for the line comment style in the extension - `//` is also supported in Inno setup, could that be added too?

FYI, I mean in the `[setup]` etc. sections, I see that `\\` is already supported in the `[code]` section

**Comment by idleberg** [comment]
I cannot find documentation for this. It's possible to add a second comment delimiter to the syntax definition, but as far as I know only one can be used to toggle comments.

**Comment by pzhlkj6612** [comment]
Hi, @dylankenneally .

> I see that `\\` is already supported in the `[code]` section

I guess you mean "I see that `//` is already supported in the `[code]` section", right?

**Comment by pzhlkj6612** [comment]
> ... but as far as I know only one can be used to toggle comments.

Yes, until microsoft/vscode#64659 is implemented.
