### ISSUE TITLE
Remove requirement to point to ISCC.exe

### ISSUE THREAD

**Issue by oliversalzburg** [idleberg/vscode-innosetup#8]
Part of the setup process for this extension (well, it's really the *only* thing you need to do), is to point it to `ISCC.exe`.

While I searched my computer for the full path, I realized that https://www.npmjs.com/package/innosetup-compiler is already installed in my vscode dev area. How about using that in this extension?

**Comment by idleberg** [comment]
I'm aware of this package, but personally I don't like the idea behind it. I'd rather have the user be in control of the version of `ISCC.exe` he wants to use. Also, this would potentially force me to update the extension whenever the Node package is updated (even if it appears that the development of Inno Setup has been halted.)

**Comment by oliversalzburg** [comment]
Alright. Makes sense :)
